# Dependabot will run on day 16 of each month at 03:51 (Europe/Berlin timezone)
version: 2
updates:

  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "cron"
      timezone: "Europe/Berlin"
      cronjob: "51 3 16 * *"
    open-pull-requests-limit: 20
    assignees:
      - "foxthefox"
    versioning-strategy: "increase"
